//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResultsView.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PHEV {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PHEV() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResultsView.Properties.PHEV", typeof(PHEV).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle Time.
        /// </summary>
        internal static string CycleTime {
            get {
                return ResourceManager.GetString("CycleTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Status.
        /// </summary>
        internal static string EndStatus {
            get {
                return ResourceManager.GetString("EndStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle (°).
        /// </summary>
        internal static string FoundAt {
            get {
                return ResourceManager.GetString("FoundAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image 1.
        /// </summary>
        internal static string Image1 {
            get {
                return ResourceManager.GetString("Image1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image 2.
        /// </summary>
        internal static string Image2 {
            get {
                return ResourceManager.GetString("Image2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orientation.
        /// </summary>
        internal static string OrientationStatus {
            get {
                return ResourceManager.GetString("OrientationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part present.
        /// </summary>
        internal static string PartPresent {
            get {
                return ResourceManager.GetString("PartPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part Position OK.
        /// </summary>
        internal static string PartUpsideDown {
            get {
                return ResourceManager.GetString("PartUpsideDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start ID.
        /// </summary>
        internal static string StartID {
            get {
                return ResourceManager.GetString("StartID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type ID.
        /// </summary>
        internal static string TypeID {
            get {
                return ResourceManager.GetString("TypeID", resourceCulture);
            }
        }
    }
}
